### ISSUE TITLE
Want the 3D printing case CAD files

### ISSUE THREAD

**Issue by yangbo** [Ergodox-io/ergodox-case#3]
Hello, I have 3d-printed an ergodox case using  the double bottom case, but I found the tent angle is too low, I want change the double bottom cases to increase the tent angle, so I need the CAD files for these cases. Could you upload these CAD files? Thanks a lot.

**Comment by robotmaxtron** [comment]
as far as I'm aware, there were never any CAD files available to download, only the STL files. Sorry.

**Comment by robotmaxtron** [comment]
Fixed in https://github.com/Ergodox-io/ergodox-case/pull/4
